name: Push commit
on: [push]
jobs:
  tex_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PDF upd
        uses: ./ # Uses an action in the root directory
      - name: Commit report
        run: |
          bash entrypoint.sh
          git config --global user.name 'retir'
          git config --global user.email 'retir@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "Push Resume.pdf"
          git push
