name: Push commit
on: [push]
jobs:
  tex_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PDF upd
        uses: ./ # Uses an action in the root directory
      - name: Commit report
        run: |
          ls
